/**
 * PYQ Bank — CBSE Class 10 previous year questions (2015–2025),
 * chapter-wise, with board marking-scheme points.
 */
import { SUBJECTS } from "./curriculum";

export type Pyq = {
  id: string;
  subjectId: string;
  chapterId: string;
  year: number;
  marks: 1 | 2 | 3 | 4 | 5;
  question: string;
  /** Board marking-scheme points — each point is what the examiner awards marks for. */
  scheme: string[];
};

const P = (
  id: string,
  subjectId: string,
  chapterId: string,
  year: number,
  marks: Pyq["marks"],
  question: string,
  scheme: string[],
): Pyq => ({ id, subjectId, chapterId, year, marks, question, scheme });

export const PYQS: Pyq[] = [
  // ---------------- SCIENCE ----------------
  P("pyq-sc-cr-1", "science", "chemical-reactions", 2023, 3,
    "Balance the following chemical equations and identify the type of reaction: (a) Fe + Cl₂ → FeCl₃ (b) CaCO₃ → CaO + CO₂ (c) H₂ + Cl₂ → 2HCl",
    ["½ mark for each correctly balanced equation", "½ mark for each correct type: combination / decomposition / combination", "States or conditions written correctly fetch full credit"]),
  P("pyq-sc-cr-2", "science", "chemical-reactions", 2019, 3,
    "What is a redox reaction? When a magnesium ribbon burns in air, identify the substance oxidised and the substance reduced.",
    ["1 mark: reaction where oxidation and reduction occur together", "1 mark: Mg is oxidised to MgO (gains oxygen)", "1 mark: O₂ is reduced"]),
  P("pyq-sc-cr-3", "science", "chemical-reactions", 2016, 2,
    "Why does the colour of copper sulphate solution change when an iron nail is dipped in it?",
    ["1 mark: Fe is more reactive than Cu, displaces it", "1 mark: blue CuSO₄ changes to green FeSO₄"]),
  P("pyq-sc-abs-1", "science", "acids-bases-salts", 2024, 3,
    "A white powder is used by doctors to support fractured bones. (a) Identify the powder and write its chemical formula. (b) Write the equation for its preparation. (c) What is it called when it loses its water of crystallisation?",
    ["1 mark: Plaster of Paris, CaSO₄·½H₂O", "1 mark: CaSO₄·2H₂O →(373 K) CaSO₄·½H₂O + 1½H₂O", "1 mark: anhydrous calcium sulphate (dead burnt plaster)"]),
  P("pyq-sc-abs-2", "science", "acids-bases-salts", 2020, 3,
    "Define pH scale. What is the pH range of our stomach and of tooth decay? How is tooth decay prevented?",
    ["1 mark: pH scale 0–14 measures acidity/alkalinity", "1 mark: stomach ≈ 1.2–2, decay below pH 5.5", "1 mark: toothpaste (basic) neutralises excess acid"]),
  P("pyq-sc-abs-3", "science", "acids-bases-salts", 2017, 2,
    "Write the chemical name and formula of washing soda. State one use.",
    ["½ mark: sodium carbonate decahydrate", "½ mark: Na₂CO₃·10H₂O", "1 mark: use — softening hard water / glass, soap industry"]),
  P("pyq-sc-mn-1", "science", "metals-nonmetals", 2022, 3,
    "Explain with equations how sodium, aluminium and iron react with water.",
    ["1 mark: 2Na + 2H₂O → 2NaOH + H₂ (violent, cold water)", "1 mark: 2Al + 3H₂O → Al₂O₃ + 3H₂ (steam)", "1 mark: 3Fe + 4H₂O → Fe₃O₄ + 4H₂ (red-hot iron + steam)"]),
  P("pyq-sc-mn-2", "science", "metals-nonmetals", 2018, 3,
    "What is an alloy? Write the composition of brass and bronze. Why are alloys used for making electrical heating devices?",
    ["1 mark: homogeneous mixture of metals (or metal + non-metal)", "1 mark: brass = Cu + Zn; bronze = Cu + Sn", "1 mark: alloys have higher resistivity and don't oxidise easily at high temperature"]),
  P("pyq-sc-cc-1", "science", "carbon-compounds", 2023, 3,
    "What is a homologous series? Write the general formula of alkanes and draw the structure of butane.",
    ["1 mark: series of compounds with same functional group, differing by –CH₂–", "1 mark: CₙH₂ₙ₊₂", "1 mark: correct structural formula of butane CH₃–CH₂–CH₂–CH₃"]),
  P("pyq-sc-cc-2", "science", "carbon-compounds", 2019, 3,
    "Distinguish between soap and detergent. Why do soaps not work in hard water?",
    ["1 mark: soap = sodium salt of fatty acid; detergent = ammonium/sulphonate salt", "2 marks: soaps form scum with Ca²⁺/Mg²⁺ ions of hard water; detergents remain effective"]),
  P("pyq-sc-lp-1", "science", "life-processes", 2024, 5,
    "(a) Draw a labelled diagram of the human alimentary canal. (b) Write the role of HCl in the stomach. (c) Where does complete digestion occur?",
    ["2 marks: diagram with 4+ correct labels (oesophagus, stomach, liver, small intestine…)", "2 marks: HCl makes medium acidic for pepsin, kills germs", "1 mark: complete digestion in small intestine"]),
  P("pyq-sc-lp-2", "science", "life-processes", 2021, 3,
    "List three differences between aerobic and anaerobic respiration.",
    ["1 mark each: oxygen used vs not; complete vs incomplete breakdown; more vs less energy released", "Equations for both fetch full credit"]),
  P("pyq-sc-lp-3", "science", "life-processes", 2016, 3,
    "How is transport of water and minerals different from transport of food in plants?",
    ["1 mark: water/minerals via xylem, upward by transpiration pull", "1 mark: food via phloem, both directions (translocation)", "1 mark: translocation needs ATP energy; transpiration pull is passive"]),
  P("pyq-sc-cnc-1", "science", "control-coordination", 2022, 3,
    "What is a reflex arc? Draw its pathway. Why is the reflex action important?",
    ["1 mark: definition — pathway of reflex action", "1 mark: receptor → sensory neuron → spinal cord → motor neuron → effector", "1 mark: saves time, protects from harm"]),
  P("pyq-sc-cnc-2", "science", "control-coordination", 2018, 3,
    "Name the plant hormones responsible for: (a) cell elongation (b) fruit ripening (c) wilting of leaves.",
    ["1 mark: auxin", "1 mark: ethylene", "1 mark: abscisic acid (ABA)"]),
  P("pyq-sc-li-1", "science", "light", 2024, 3,
    "An object 4 cm tall is placed 20 cm in front of a concave mirror of focal length 15 cm. Find the position, nature and size of the image.",
    ["1 mark: 1/v + 1/u = 1/f with correct sign convention", "1 mark: v = −60 cm (real, in front of mirror)", "1 mark: m = −3, image 12 cm, real and inverted"]),
  P("pyq-sc-li-2", "science", "light", 2020, 5,
    "(a) State the laws of refraction. (b) The refractive index of glass is 1.5. Find the speed of light in glass (c = 3 × 10⁸ m/s). (c) What is absolute refractive index?",
    ["2 marks: Snell's law + incident/refracted ray and normal in same plane", "2 marks: v = c/n = 2 × 10⁸ m/s", "1 mark: refractive index w.r.t. vacuum/air"]),
  P("pyq-sc-li-3", "science", "light", 2015, 2,
    "Why does the sky appear blue? Why does the sun appear reddish at sunrise?",
    ["1 mark: shorter blue wavelengths scatter most (Rayleigh scattering)", "1 mark: at sunrise light travels longer path; blue scattered away, red remains"]),
  P("pyq-sc-el-1", "science", "electricity", 2023, 3,
    "Three resistors of 5Ω, 10Ω and 15Ω are connected in series to a 12V battery. Find the equivalent resistance and the current in the circuit.",
    ["1 mark: R = 5 + 10 + 15 = 30Ω", "1 mark: I = V/R", "1 mark: I = 12/30 = 0.4 A"]),
  P("pyq-sc-el-2", "science", "electricity", 2019, 3,
    "State Ohm's law. Draw the V–I graph for a metallic conductor and write two factors affecting resistance.",
    ["1 mark: V ∝ I at constant temperature (V = IR)", "1 mark: straight line through origin", "½ + ½ mark: length, area of cross-section (material/temperature also accepted)"]),
  P("pyq-sc-el-3", "science", "electricity", 2016, 3,
    "An electric bulb is rated 100 W, 220 V. Calculate its resistance and the energy consumed in 4 hours.",
    ["1 mark: R = V²/P = 484 Ω", "1 mark: E = P × t = 0.1 kW × 4 h", "1 mark: 0.4 kWh (units)"]),
  P("pyq-sc-me-1", "science", "magnetic-effects", 2022, 3,
    "State Fleming's left-hand rule. Name two devices based on the magnetic effect of current and explain one.",
    ["1 mark: rule stated with thumb/forefinger/central finger directions", "1 mark: electric motor, galvanometer", "1 mark: explanation of force on current-carrying coil in magnetic field"]),
  P("pyq-sc-me-2", "science", "magnetic-effects", 2017, 3,
    "What is electromagnetic induction? State Faraday's experiment and one application.",
    ["1 mark: induced current due to changing magnetic flux", "1 mark: moving magnet into/out of coil deflects galvanometer", "1 mark: electric generator / transformer"]),

  // ---------------- MATHS ----------------
  P("pyq-ma-rn-1", "maths", "real-numbers", 2024, 3,
    "Prove that √5 is an irrational number.",
    ["1 mark: assume √5 = p/q in lowest terms", "1 mark: show 5 divides p and hence 5 divides q", "1 mark: contradiction of coprimality, hence irrational"]),
  P("pyq-ma-rn-2", "maths", "real-numbers", 2018, 2,
    "Use Euclid's division lemma to show that the square of any positive integer is of the form 3m or 3m + 1.",
    ["1 mark: write a = 3q, 3q+1, 3q+2", "1 mark: square each case to get 3m or 3m+1"]),
  P("pyq-ma-po-1", "maths", "polynomials", 2023, 2,
    "Find the zeroes of the polynomial x² − 3x − 10 and verify the relationship between the zeroes and coefficients.",
    ["1 mark: zeroes 5 and −2 by factorisation", "1 mark: sum = 3 = −(−3)/1, product = −10 = c/a"]),
  P("pyq-ma-po-2", "maths", "polynomials", 2019, 3,
    "If α and β are the zeroes of p(x) = 2x² − 5x + 1, find a quadratic polynomial whose zeroes are 2α and 2β.",
    ["1 mark: α + β = 5/2, αβ = 1/2", "1 mark: new sum = 5, new product = 2", "1 mark: k(x² − 5x + 2)"]),
  P("pyq-ma-le-1", "maths", "linear-equations", 2022, 3,
    "For what value of k will the system kx + 3y = k − 3 and 12x + ky = k have no solution?",
    ["1 mark: condition a₁/a₂ = b₁/b₂ ≠ c₁/c₂", "1 mark: k/12 = 3/k ⇒ k² = 36 ⇒ k = ±6", "1 mark: reject k = 6 (gives infinite solutions); k = −6"]),
  P("pyq-ma-le-2", "maths", "linear-equations", 2016, 3,
    "Solve: 2/x + 3/y = 13 and 5/x − 4/y = −2.",
    ["1 mark: substitute 1/x = u, 1/y = v", "1 mark: solve 2u + 3v = 13, 5u − 4v = −2 → u = 2, v = 3", "1 mark: x = 1/2, y = 1/3"]),
  P("pyq-ma-qe-1", "maths", "quadratic-equations", 2024, 3,
    "Find the nature of roots of 2x² − 4x + 3 = 0. If real, find them.",
    ["1 mark: D = b² − 4ac = 16 − 24 = −8", "1 mark: D < 0 ⇒ no real roots", "1 mark: correct interpretation (roots are imaginary)"]),
  P("pyq-ma-qe-2", "maths", "quadratic-equations", 2020, 3,
    "A train travels 360 km at a uniform speed. If the speed had been 5 km/h more, it would have taken 1 hour less. Find the speed of the train.",
    ["1 mark: 360/x − 360/(x+5) = 1", "1 mark: x² + 5x − 1800 = 0", "1 mark: x = 40 km/h (reject −45)"]),
  P("pyq-ma-ap-1", "maths", "ap", 2023, 3,
    "How many terms of the AP 9, 17, 25, … must be taken to give a sum of 636?",
    ["1 mark: Sₙ = n/2 [2a + (n−1)d] with a = 9, d = 8", "1 mark: 4n² + 5n − 636 = 0", "1 mark: n = 12 (reject negative root)"]),
  P("pyq-ma-ap-2", "maths", "ap", 2017, 2,
    "Which term of the AP 3, 8, 13, 18, … is 78?",
    ["1 mark: aₙ = a + (n−1)d ⇒ 78 = 3 + (n−1)5", "1 mark: n = 16th term"]),
  P("pyq-ma-tr-1", "maths", "triangles", 2022, 3,
    "State and prove the Basic Proportionality Theorem (Thales theorem).",
    ["1 mark: correct statement", "1 mark: construction — join B to E and C to D, draw perpendiculars", "1 mark: areas ratio proof AD/DB = AE/EC"]),
  P("pyq-ma-tr-2", "maths", "triangles", 2019, 3,
    "In ΔABC, AD is the median. Prove that AB² + AC² = 2AD² + 2BD² (Apollonius theorem).",
    ["1 mark: draw AE ⊥ BC", "1 mark: apply Pythagoras in ΔAEB and ΔAEC", "1 mark: combine using BD = DC and ED relations"]),
  P("pyq-ma-cg-1", "maths", "coordinate-geometry", 2024, 2,
    "Find the distance between points (2, 3) and (−4, 1).",
    ["1 mark: d = √[(x₂−x₁)² + (y₂−y₁)²]", "1 mark: √[36 + 4] = 2√10 units"]),
  P("pyq-ma-cg-2", "maths", "coordinate-geometry", 2018, 3,
    "Find the ratio in which the point (−4, 6) divides the line segment joining A(−6, 10) and B(3, −8).",
    ["1 mark: section formula −4 = (3k − 6)/(k + 1)", "1 mark: solve k = 2/7", "1 mark: ratio 2 : 7"]),
  P("pyq-ma-tg-1", "maths", "trigonometry", 2023, 3,
    "Prove: (sin θ − cos θ + 1)/(sin θ + cos θ − 1) = 1/(sec θ − tan θ).",
    ["1 mark: divide numerator & denominator by cos θ", "1 mark: convert to tan & sec and use sec²θ − tan²θ = 1", "1 mark: LHS = RHS simplification"]),
  P("pyq-ma-tg-2", "maths", "trigonometry", 2015, 2,
    "If tan A = 4/3, find the value of (sin A + cos A)/(sin A − cos A).",
    ["1 mark: divide by cos A → (tan A + 1)/(tan A − 1)", "1 mark: (4/3 + 1)/(4/3 − 1) = 7"]),
  P("pyq-ma-ci-1", "maths", "circles", 2024, 3,
    "Prove that the lengths of tangents drawn from an external point to a circle are equal.",
    ["1 mark: construction — join O to P, A, B", "1 mark: ΔOAP ≅ ΔOBP (RHS)", "1 mark: PA = PB (CPCT)"]),
  P("pyq-ma-ci-2", "maths", "circles", 2019, 2,
    "Two concentric circles have radii 5 cm and 3 cm. Find the length of the chord of the larger circle which touches the smaller circle.",
    ["1 mark: radius to tangent point ⊥ chord, bisects it", "1 mark: half chord = √(25 − 9) = 4, chord = 8 cm"]),
  P("pyq-ma-sv-1", "maths", "surface-areas", 2022, 3,
    "A solid iron cuboid 49 cm × 33 cm × 24 cm is melted to form a sphere. Find the radius of the sphere.",
    ["1 mark: volume of cuboid = 49 × 33 × 24 = 38808 cm³", "1 mark: (4/3)πr³ = 38808", "1 mark: r³ = 9261 ⇒ r = 21 cm"]),
  P("pyq-ma-sv-2", "maths", "surface-areas", 2016, 3,
    "A tent is cylindrical up to 3 m height and conical above it, with base diameter 105 m and slant height 53 m. Find the canvas required.",
    ["1 mark: CSA cylinder = 2πrh = 990 m²", "1 mark: CSA cone = πrl = 8745 m²", "1 mark: total = 9735 m²"]),
  P("pyq-ma-st-1", "maths", "statistics", 2023, 3,
    "The mean of the following frequency distribution is 62.8. Find the missing frequency f. (Classes 0–20, 20–40, 40–60, 60–80, 80–100 with frequencies 5, 8, f, 12, 7)",
    ["1 mark: compute xᵢ and fᵢxᵢ table", "1 mark: Σfᵢ = 32 + f, Σfᵢxᵢ = 2060 + 50f", "1 mark: 62.8(32 + f) = 2060 + 50f ⇒ f = 4 (check arithmetic)"]),
  P("pyq-ma-st-2", "maths", "statistics", 2018, 3,
    "Write the empirical relationship between mean, median and mode. If mode = 24.5 and mean = 29.75, find the median.",
    ["1 mark: Mode = 3 Median − 2 Mean", "1 mark: 24.5 = 3M − 59.5", "1 mark: Median = 28"]),
  P("pyq-ma-pr-1", "maths", "probability", 2024, 2,
    "Two dice are thrown together. Find the probability that the sum is (a) 7 (b) a doublet.",
    ["1 mark: total outcomes 36; favourable for 7 = 6 ⇒ 1/6", "1 mark: doublets = 6 ⇒ 1/6"]),
  P("pyq-ma-pr-2", "maths", "probability", 2020, 2,
    "A card is drawn from a well-shuffled deck of 52 cards. Find the probability of getting (a) a king of red colour (b) a face card.",
    ["1 mark: 2/52 = 1/26", "1 mark: 12/52 = 3/13"]),

  // ---------------- SOCIAL SCIENCE ----------------
  P("pyq-ss-ne-1", "sst", "nationalism-europe", 2023, 3,
    "Explain any three features of the Zollverein (1834).",
    ["1 mark each: abolished tariff barriers / reduced currencies from over 30 to 2 / created economic nationalism and unified Germany economically"]),
  P("pyq-ss-ne-2", "sst", "nationalism-europe", 2019, 5,
    "Describe the process of unification of Germany.",
    ["1 mark: role of Bismarck and Prussia", "1 mark: three wars over 7 years (Denmark, Austria, France)", "1 mark: Zollverein economic groundwork", "1 mark: proclamation of Kaiser William I at Versailles, 1871", "1 mark: role of middle class, army and diplomacy"]),
  P("pyq-ss-ni-1", "sst", "nationalism-india", 2022, 5,
    "Why did Gandhiji launch the Civil Disobedience Movement? Explain its spread.",
    ["1 mark: failure of Simon Commission and demand of Purna Swaraj", "1 mark: Salt March 12 March 1930, Dandi", "1 mark: breaking salt law as symbol", "1 mark: spread — boycott, picketing, refusal to pay taxes", "1 mark: participation of women, peasants, tribals"]),
  P("pyq-ss-ni-2", "sst", "nationalism-india", 2018, 3,
    "Explain any three causes of the Non-Cooperation Movement.",
    ["1 mark each: Rowlatt Act 1919 / Jallianwala Bagh massacre / Khilafat issue"]),
  P("pyq-ss-rd-1", "sst", "resources", 2024, 3,
    "Classify resources on the basis of origin and exhaustibility with examples.",
    ["1½ marks: biotic & abiotic with examples", "1½ marks: renewable & non-renewable with examples"]),
  P("pyq-ss-rd-2", "sst", "resources", 2017, 3,
    "What is resource planning? Explain its three stages in India.",
    ["1 mark: definition", "1 mark: identification & inventory of resources", "1 mark: evolving structure + matching resource plans with development plans"]),
  P("pyq-ss-wr-1", "sst", "water-resources", 2022, 3,
    "Why are multi-purpose river valley projects called the 'temples of modern India'?",
    ["1 mark each: irrigation & agriculture / hydroelectricity / flood control, water supply, navigation (any three)"]),
  P("pyq-ss-wr-2", "sst", "water-resources", 2016, 3,
    "What is rainwater harvesting? Explain rooftop rainwater harvesting.",
    ["1 mark: collecting and storing rainwater for future use", "2 marks: rooftop collection → pipes → recharge pit/tank; common in Rajasthan & Tamil Nadu"]),
  P("pyq-ss-ps-1", "sst", "power-sharing", 2023, 3,
    "Explain the Belgian model of power sharing.",
    ["1 mark: equal representation in central government (Dutch & French)", "1 mark: state governments not subordinate to centre", "1 mark: community government for language/culture"]),
  P("pyq-ss-ps-2", "sst", "power-sharing", 2019, 3,
    "Why is power sharing desirable? Give prudential and moral reasons.",
    ["1½ marks: prudential — reduces conflict, ensures stability", "1½ marks: moral — democracy means sharing power with those affected"]),
  P("pyq-ss-fe-1", "sst", "federalism", 2024, 3,
    "Distinguish between the Union List, State List and Concurrent List.",
    ["1 mark each with one example: Union (defence), State (police), Concurrent (education)"]),
  P("pyq-ss-fe-2", "sst", "federalism", 2018, 3,
    "Explain any three features of Indian federalism.",
    ["1 mark each: three-tier government / constitutional division of powers / independent judiciary & decentralisation"]),
  P("pyq-ss-de-1", "sst", "development", 2022, 3,
    "Why do different people have different notions of development? Explain with examples.",
    ["1 mark: development goals depend on life situations", "1 mark: example — farmer wants irrigation, girl wants freedom/education", "1 mark: conflicting goals example — dam builders vs displaced tribals"]),
  P("pyq-ss-de-2", "sst", "development", 2019, 3,
    "What is HDI? Which three indicators does it use?",
    ["1 mark: Human Development Index by UNDP", "2 marks: per capita income, life expectancy, education (literacy + enrolment)"]),
  P("pyq-ss-se-1", "sst", "sectors-economy", 2023, 3,
    "Explain the three sectors of economic activities with examples.",
    ["1 mark each: primary (agriculture), secondary (manufacturing), tertiary (services) with examples"]),
  P("pyq-ss-se-2", "sst", "sectors-economy", 2016, 3,
    "What is MGNREGA? State its main objectives.",
    ["1 mark: Mahatma Gandhi National Rural Employment Guarantee Act, 2005", "2 marks: 100 days guaranteed wage employment / asset creation / livelihood security in rural areas"]),

  // ---------------- ENGLISH ----------------
  P("pyq-en-ff-1", "english", "first-flight", 2023, 5,
    "Describe the character of Lencho in 'A Letter to God'. Why did he write a letter to God?",
    ["1 mark: Lencho — hardworking, simple farmer with deep faith", "1 mark: hailstorm destroyed his crop", "1 mark: wrote letter asking for 100 pesos", "1 mark: unshakeable faith — expected God to reply", "1 mark: irony — suspected post office employees of stealing"]),
  P("pyq-en-ff-2", "english", "first-flight", 2019, 3,
    "What values did Nelson Mandela learn from his childhood and struggle?",
    ["1 mark each: freedom is indivisible / courage is triumph over fear / both oppressor and oppressed must be liberated"]),
  P("pyq-en-po-1", "english", "poems", 2022, 3,
    "How does Robert Frost use 'fire' and 'ice' as symbols in the poem 'Fire and Ice'?",
    ["1 mark: fire = desire, greed, lust", "1 mark: ice = hatred, coldness, indifference", "1 mark: both emotions can destroy the world; poem is a warning"]),
  P("pyq-en-fp-1", "english", "footprints", 2024, 3,
    "How did Ausable outwit Max in 'The Midnight Visitor'?",
    ["1 mark: Ausable fabricated the story of a balcony", "1 mark: knocked-on-door bluff about the police", "1 mark: Max jumped to his death; presence of mind won over weapons"]),
  P("pyq-en-gr-1", "english", "grammar", 2021, 1,
    "Change into indirect speech: He said, 'I have finished my work.'",
    ["1 mark: He said that he had finished his work. (backshift of tense + pronoun change)"]),
  P("pyq-en-wr-1", "english", "writing", 2023, 5,
    "Write a letter to the Editor of a national daily about the rising problem of plastic pollution in your city (100–120 words).",
    ["1 mark: correct format (sender, date, receiver, subject, salutation)", "2 marks: content — problem, causes, effects, suggestions", "1 mark: coherence and paragraphing", "1 mark: accuracy of grammar and spelling"]),

  // ---------------- HINDI ----------------
  P("pyq-hi-kk-1", "hindi", "kshitij-kavya", 2022, 3,
    "सूरदास के पदों में वात्सल्य रस की विशेषताएँ स्पष्ट कीजिए।",
    ["1 अंक: माता यशोदा का बालकृष्ण प्रति अपार प्रेम", "1 अंक: बाल-लीलाओं का सजीव चित्रण", "1 अंक: सरल ब्रजभाषा और भावपूर्ण शैली"]),
  P("pyq-hi-kg-1", "hindi", "kshitij-gadya", 2023, 3,
    "'नेताजी का चश्मा' में स्वयं सेवक की मनोदशा का चित्रण कीजिए।",
    ["1 अंक: सेवा-भाव से प्रेरित होकर कांटा निकालना", "1 अंक: भ्रम — कप्तान साहब को नेताजी समझ लेना", "1 अंक: निष्काम सेवा की भावना"]),
  P("pyq-hi-kr-1", "hindi", "kritika", 2019, 3,
    "'माता का अँचल' पाठ में माता-पुत्र के संबंध की विशेषता बताइए।",
    ["1 अंक: माता का अपने सीधे-सादे पुत्र प्रति स्नेह", "1 अंक: दूधवाले से बदमाशी का प्रसंग", "1 अंक: अँचल — सुरक्षा और ममता का प्रतीक"]),
  P("pyq-hi-vy-1", "hindi", "vyakaran", 2024, 2,
    "'विद्यालय' और 'राजपुत्र' में समास की पहचान कीजिए और विग्रह लिखिए।",
    ["1 अंक: विद्यालय = विद्या के लिए आलय (संप्रदान तत्पुरुष)", "1 अंक: राजपुत्र = राजा का पुत्र (षष्ठी तत्पुरुष)"]),
];

export const PYQ_YEARS = Array.from(new Set(PYQS.map((q) => q.year))).sort((a, b) => b - a);

export function pyqsFor(subjectId: string, chapterId?: string): Pyq[] {
  return PYQS.filter(
    (q) => q.subjectId === subjectId && (!chapterId || chapterId === "all" || q.chapterId === chapterId),
  ).sort((a, b) => b.year - a.year);
}

export function pyqCountByChapter(subjectId: string): Map<string, number> {
  const map = new Map<string, number>();
  for (const q of PYQS) {
    if (q.subjectId !== subjectId) continue;
    map.set(q.chapterId, (map.get(q.chapterId) ?? 0) + 1);
  }
  return map;
}

export function pyqSubjectCounts(): Map<string, number> {
  const map = new Map<string, number>();
  for (const s of SUBJECTS) map.set(s.id, PYQS.filter((q) => q.subjectId === s.id).length);
  return map;
}
