import type { Question } from "./curriculum";

/**
 * Extra CBSE Class 10 seed questions.
 *
 * These ship with the app so that full 30-question mock tests can be generated
 * even before the owner imports a CSV into the cloud question bank.
 */
export const EXTRA_QUESTIONS: Question[] = [
  // ---------------------------------------------------------------- SCIENCE
  {
    id: "x-sci-1",
    subjectId: "science",
    chapterId: "chemical-reactions",
    difficulty: "easy",
    question: "The reaction 2Mg + O₂ → 2MgO is an example of:",
    options: ["Decomposition", "Combination", "Displacement", "Double displacement"],
    answer: 1,
    explanation: "Two reactants combine to form a single product, so it is a combination reaction.",
    concept: "Types of chemical reactions",
  },
  {
    id: "x-sci-2",
    subjectId: "science",
    chapterId: "chemical-reactions",
    difficulty: "medium",
    question: "Rancidity of food can be prevented by packing chips in a bag flushed with:",
    options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"],
    answer: 2,
    explanation: "Nitrogen is unreactive, so it prevents oxidation of the fats and oils in the chips.",
    concept: "Corrosion and rancidity",
  },
  {
    id: "x-sci-3",
    subjectId: "science",
    chapterId: "chemical-reactions",
    difficulty: "medium",
    question: "In the reaction Pb(NO₃)₂ + 2KI → PbI₂ + 2KNO₃, the yellow precipitate is:",
    options: ["KNO₃", "PbI₂", "KI", "Pb(NO₃)₂"],
    answer: 1,
    explanation: "Lead iodide (PbI₂) is insoluble and separates out as a bright yellow precipitate.",
    concept: "Double displacement reactions",
  },
  {
    id: "x-sci-4",
    subjectId: "science",
    chapterId: "acids-bases-salts",
    difficulty: "medium",
    question: "Which gas is produced when a metal reacts with a dilute acid?",
    options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Chlorine"],
    answer: 1,
    explanation: "Metal + dilute acid → salt + hydrogen gas, which burns with a pop sound.",
    concept: "Reactions of acids",
  },
  {
    id: "x-sci-5",
    subjectId: "science",
    chapterId: "acids-bases-salts",
    difficulty: "easy",
    question: "The chemical formula of washing soda is:",
    options: ["NaHCO₃", "Na₂CO₃·10H₂O", "CaOCl₂", "CaSO₄·½H₂O"],
    answer: 1,
    explanation: "Washing soda is sodium carbonate decahydrate, Na₂CO₃·10H₂O.",
    concept: "Common salts",
  },
  {
    id: "x-sci-6",
    subjectId: "science",
    chapterId: "acids-bases-salts",
    difficulty: "hard",
    question: "A solution turns red litmus blue. Its pH is likely to be:",
    options: ["1", "4", "5", "10"],
    answer: 3,
    explanation: "Only basic solutions turn red litmus blue, and bases have pH greater than 7.",
    concept: "pH scale",
  },
  {
    id: "x-sci-7",
    subjectId: "science",
    chapterId: "metals-nonmetals",
    difficulty: "easy",
    question: "Which of the following metals is stored under kerosene?",
    options: ["Copper", "Sodium", "Iron", "Gold"],
    answer: 1,
    explanation: "Sodium reacts vigorously with air and water, so it is kept under kerosene.",
    concept: "Reactivity of metals",
  },
  {
    id: "x-sci-8",
    subjectId: "science",
    chapterId: "metals-nonmetals",
    difficulty: "medium",
    question: "Galvanisation is the coating of iron with a layer of:",
    options: ["Tin", "Zinc", "Chromium", "Nickel"],
    answer: 1,
    explanation: "Zinc is more reactive than iron and protects it from rusting even if the layer is scratched.",
    concept: "Prevention of corrosion",
  },
  {
    id: "x-sci-9",
    subjectId: "science",
    chapterId: "metals-nonmetals",
    difficulty: "medium",
    question: "Which of the following is an amphoteric oxide?",
    options: ["Na₂O", "Al₂O₃", "CaO", "MgO"],
    answer: 1,
    explanation: "Aluminium oxide reacts with both acids and bases, so it is amphoteric.",
    concept: "Oxides of metals",
  },
  {
    id: "x-sci-10",
    subjectId: "science",
    chapterId: "carbon-compounds",
    difficulty: "easy",
    question: "The functional group present in ethanoic acid is:",
    options: ["–OH", "–CHO", "–COOH", "–CO–"],
    answer: 2,
    explanation: "Ethanoic acid (CH₃COOH) contains the carboxylic acid group –COOH.",
    concept: "Functional groups",
  },
  {
    id: "x-sci-11",
    subjectId: "science",
    chapterId: "carbon-compounds",
    difficulty: "medium",
    question: "Two consecutive members of a homologous series differ by:",
    options: ["CH₂", "CH₃", "C₂H₆", "CH₄"],
    answer: 0,
    explanation: "Successive members differ by one –CH₂– unit, i.e. 14 u of mass.",
    concept: "Homologous series",
  },
  {
    id: "x-sci-12",
    subjectId: "science",
    chapterId: "carbon-compounds",
    difficulty: "hard",
    question: "Soap does not clean well in hard water because hard water contains:",
    options: ["Sodium ions", "Calcium and magnesium ions", "Chloride ions", "Nitrate ions"],
    answer: 1,
    explanation: "Ca²⁺ and Mg²⁺ ions form insoluble scum with soap, wasting it.",
    concept: "Soaps and detergents",
  },
  {
    id: "x-sci-13",
    subjectId: "science",
    chapterId: "life-processes",
    difficulty: "easy",
    question: "The opening and closing of stomata is controlled by:",
    options: ["Epidermal cells", "Guard cells", "Xylem vessels", "Phloem cells"],
    answer: 1,
    explanation: "Guard cells swell or shrink with water, opening or closing the stomatal pore.",
    concept: "Transpiration",
  },
  {
    id: "x-sci-14",
    subjectId: "science",
    chapterId: "life-processes",
    difficulty: "medium",
    question: "The functional unit of the kidney is the:",
    options: ["Neuron", "Nephron", "Alveolus", "Villus"],
    answer: 1,
    explanation: "Each kidney contains about a million nephrons which filter blood to form urine.",
    concept: "Excretion",
  },
  {
    id: "x-sci-15",
    subjectId: "science",
    chapterId: "life-processes",
    difficulty: "medium",
    question: "Transport of food in plants takes place through:",
    options: ["Xylem", "Phloem", "Cambium", "Cortex"],
    answer: 1,
    explanation: "Translocation of food occurs through phloem, using energy from ATP.",
    concept: "Transportation in plants",
  },
  {
    id: "x-sci-16",
    subjectId: "science",
    chapterId: "control-coordination",
    difficulty: "medium",
    question: "Which hormone regulates blood sugar level?",
    options: ["Thyroxine", "Insulin", "Adrenaline", "Testosterone"],
    answer: 1,
    explanation: "Insulin, secreted by the pancreas, lowers blood glucose level.",
    concept: "Hormones in animals",
  },
  {
    id: "x-sci-17",
    subjectId: "science",
    chapterId: "control-coordination",
    difficulty: "easy",
    question: "The gap between two neurons is called a:",
    options: ["Dendrite", "Axon", "Synapse", "Reflex arc"],
    answer: 2,
    explanation: "A synapse is the junction where a nerve impulse passes from one neuron to the next.",
    concept: "Nervous system",
  },
  {
    id: "x-sci-18",
    subjectId: "science",
    chapterId: "control-coordination",
    difficulty: "hard",
    question: "Bending of a plant shoot towards light is called:",
    options: ["Geotropism", "Hydrotropism", "Phototropism", "Chemotropism"],
    answer: 2,
    explanation: "Growth movement in response to light is phototropism, caused by uneven auxin distribution.",
    concept: "Tropic movements",
  },
  {
    id: "x-sci-19",
    subjectId: "science",
    chapterId: "light",
    difficulty: "medium",
    question: "The power of a lens of focal length 25 cm is:",
    options: ["+2 D", "+4 D", "+0.25 D", "+25 D"],
    answer: 1,
    explanation: "P = 1/f (in metres) = 1/0.25 = +4 dioptre.",
    concept: "Power of a lens",
  },
  {
    id: "x-sci-20",
    subjectId: "science",
    chapterId: "light",
    difficulty: "easy",
    question: "A convex mirror always forms an image that is:",
    options: ["Real and inverted", "Virtual and enlarged", "Virtual, erect and diminished", "Real and diminished"],
    answer: 2,
    explanation: "Whatever the object position, a convex mirror gives a virtual, erect, diminished image.",
    concept: "Spherical mirrors",
  },
  {
    id: "x-sci-21",
    subjectId: "science",
    chapterId: "light",
    difficulty: "hard",
    question: "Light travels fastest in:",
    options: ["Glass", "Water", "Vacuum", "Diamond"],
    answer: 2,
    explanation: "Vacuum has the least optical density (refractive index 1), so light is fastest there.",
    concept: "Refractive index",
  },
  {
    id: "x-sci-22",
    subjectId: "science",
    chapterId: "electricity",
    difficulty: "easy",
    question: "The SI unit of electric charge is:",
    options: ["Ampere", "Volt", "Coulomb", "Ohm"],
    answer: 2,
    explanation: "Charge is measured in coulomb; 1 A = 1 C/s.",
    concept: "Electric current",
  },
  {
    id: "x-sci-23",
    subjectId: "science",
    chapterId: "electricity",
    difficulty: "medium",
    question: "An electric bulb is rated 220 V and 100 W. The current drawn by it is:",
    options: ["0.45 A", "2.2 A", "4.5 A", "0.22 A"],
    answer: 0,
    explanation: "I = P/V = 100/220 ≈ 0.45 A.",
    concept: "Electric power",
  },
  {
    id: "x-sci-24",
    subjectId: "science",
    chapterId: "electricity",
    difficulty: "hard",
    question: "If the length of a wire is doubled keeping the area the same, its resistance:",
    options: ["Halves", "Doubles", "Remains same", "Becomes four times"],
    answer: 1,
    explanation: "R = ρl/A, so resistance is directly proportional to length.",
    concept: "Resistivity",
  },
  {
    id: "x-sci-25",
    subjectId: "science",
    chapterId: "magnetic-effects",
    difficulty: "medium",
    question: "The direction of force on a current-carrying conductor in a magnetic field is given by:",
    options: [
      "Fleming's right-hand rule",
      "Fleming's left-hand rule",
      "Right-hand thumb rule",
      "Lenz's law",
    ],
    answer: 1,
    explanation: "Fleming's left-hand rule gives the direction of force (motor effect).",
    concept: "Force on a conductor",
  },
  {
    id: "x-sci-26",
    subjectId: "science",
    chapterId: "magnetic-effects",
    difficulty: "easy",
    question: "Magnetic field lines never intersect because:",
    options: [
      "They are imaginary",
      "Two directions of field at a point are impossible",
      "They repel each other",
      "They start from the south pole",
    ],
    answer: 1,
    explanation: "If they crossed, the compass needle would point in two directions at that point, which is impossible.",
    concept: "Magnetic field lines",
  },
  {
    id: "x-sci-27",
    subjectId: "science",
    chapterId: "magnetic-effects",
    difficulty: "medium",
    question: "In a domestic circuit, the earth wire is used to:",
    options: [
      "Increase current",
      "Provide a low-resistance path to the ground",
      "Reduce voltage",
      "Store charge",
    ],
    answer: 1,
    explanation: "The earth wire safely conducts leakage current to the ground and prevents electric shock.",
    concept: "Domestic electric circuits",
  },

  // ------------------------------------------------------------------ MATHS
  {
    id: "x-mat-1",
    subjectId: "maths",
    chapterId: "real-numbers",
    difficulty: "easy",
    question: "The LCM of 12 and 18 is:",
    options: ["6", "24", "36", "72"],
    answer: 2,
    explanation: "12 = 2²×3, 18 = 2×3². LCM = 2²×3² = 36.",
    concept: "HCF and LCM",
  },
  {
    id: "x-mat-2",
    subjectId: "maths",
    chapterId: "real-numbers",
    difficulty: "medium",
    question: "If HCF(a, b) = 9 and LCM(a, b) = 90, then a × b equals:",
    options: ["99", "810", "81", "900"],
    answer: 1,
    explanation: "For two numbers, HCF × LCM = product of the numbers = 9 × 90 = 810.",
    concept: "HCF × LCM property",
  },
  {
    id: "x-mat-3",
    subjectId: "maths",
    chapterId: "real-numbers",
    difficulty: "hard",
    question: "The decimal expansion of 13/3125 will:",
    options: ["Terminate", "Be non-terminating repeating", "Be irrational", "Not exist"],
    answer: 0,
    explanation: "3125 = 5⁵, of the form 2ᵐ5ⁿ, so the decimal expansion terminates.",
    concept: "Decimal expansions",
  },
  {
    id: "x-mat-4",
    subjectId: "maths",
    chapterId: "polynomials",
    difficulty: "medium",
    question: "If α and β are zeroes of x² − 5x + 6, then α + β is:",
    options: ["5", "−5", "6", "−6"],
    answer: 0,
    explanation: "Sum of zeroes = −b/a = 5.",
    concept: "Zeroes and coefficients",
  },
  {
    id: "x-mat-5",
    subjectId: "maths",
    chapterId: "polynomials",
    difficulty: "easy",
    question: "The number of zeroes a quadratic polynomial can have is at most:",
    options: ["1", "2", "3", "4"],
    answer: 1,
    explanation: "A polynomial of degree n has at most n zeroes.",
    concept: "Degree and zeroes",
  },
  {
    id: "x-mat-6",
    subjectId: "maths",
    chapterId: "linear-equations",
    difficulty: "medium",
    question: "The pair 2x + 3y = 7 and 4x + 6y = 14 has:",
    options: ["No solution", "A unique solution", "Infinitely many solutions", "Exactly two solutions"],
    answer: 2,
    explanation: "a₁/a₂ = b₁/b₂ = c₁/c₂ = 1/2, so the lines are coincident and there are infinitely many solutions.",
    concept: "Consistency of linear pairs",
  },
  {
    id: "x-mat-7",
    subjectId: "maths",
    chapterId: "linear-equations",
    difficulty: "hard",
    question: "For what value of k does kx + 2y = 5 and 3x + y = 1 have a unique solution?",
    options: ["k = 6", "k ≠ 6", "k = 3", "k ≠ 3"],
    answer: 1,
    explanation: "Unique solution needs a₁/a₂ ≠ b₁/b₂, i.e. k/3 ≠ 2/1, so k ≠ 6.",
    concept: "Condition for unique solution",
  },
  {
    id: "x-mat-8",
    subjectId: "maths",
    chapterId: "quadratic-equations",
    difficulty: "medium",
    question: "The discriminant of 3x² − 2x + 1 = 0 is:",
    options: ["−8", "8", "4", "−4"],
    answer: 0,
    explanation: "D = b² − 4ac = 4 − 12 = −8, so the roots are not real.",
    concept: "Discriminant",
  },
  {
    id: "x-mat-9",
    subjectId: "maths",
    chapterId: "quadratic-equations",
    difficulty: "easy",
    question: "The roots of x² − 7x + 12 = 0 are:",
    options: ["3 and 4", "−3 and −4", "2 and 6", "1 and 12"],
    answer: 0,
    explanation: "x² − 7x + 12 = (x − 3)(x − 4), so x = 3, 4.",
    concept: "Factorisation method",
  },
  {
    id: "x-mat-10",
    subjectId: "maths",
    chapterId: "ap",
    difficulty: "easy",
    question: "The 10th term of the AP 2, 5, 8, … is:",
    options: ["26", "29", "30", "32"],
    answer: 1,
    explanation: "aₙ = a + (n − 1)d = 2 + 9×3 = 29.",
    concept: "nth term of an AP",
  },
  {
    id: "x-mat-11",
    subjectId: "maths",
    chapterId: "ap",
    difficulty: "medium",
    question: "The sum of the first 20 natural numbers is:",
    options: ["190", "200", "210", "220"],
    answer: 2,
    explanation: "Sₙ = n(n + 1)/2 = 20 × 21/2 = 210.",
    concept: "Sum of n terms",
  },
  {
    id: "x-mat-12",
    subjectId: "maths",
    chapterId: "triangles",
    difficulty: "medium",
    question: "If two triangles are similar with ratio of sides 3 : 4, the ratio of their areas is:",
    options: ["3 : 4", "9 : 16", "6 : 8", "16 : 9"],
    answer: 1,
    explanation: "Areas of similar triangles are in the ratio of the squares of corresponding sides.",
    concept: "Areas of similar triangles",
  },
  {
    id: "x-mat-13",
    subjectId: "maths",
    chapterId: "triangles",
    difficulty: "easy",
    question: "In a right triangle with legs 6 cm and 8 cm, the hypotenuse is:",
    options: ["9 cm", "10 cm", "12 cm", "14 cm"],
    answer: 1,
    explanation: "√(6² + 8²) = √100 = 10 cm.",
    concept: "Pythagoras theorem",
  },
  {
    id: "x-mat-14",
    subjectId: "maths",
    chapterId: "coordinate-geometry",
    difficulty: "easy",
    question: "The distance between (0, 0) and (3, 4) is:",
    options: ["5", "7", "12", "25"],
    answer: 0,
    explanation: "√(3² + 4²) = √25 = 5 units.",
    concept: "Distance formula",
  },
  {
    id: "x-mat-15",
    subjectId: "maths",
    chapterId: "coordinate-geometry",
    difficulty: "medium",
    question: "The midpoint of the line segment joining (2, 3) and (6, 7) is:",
    options: ["(4, 5)", "(3, 4)", "(8, 10)", "(2, 2)"],
    answer: 0,
    explanation: "Midpoint = ((2+6)/2, (3+7)/2) = (4, 5).",
    concept: "Section formula",
  },
  {
    id: "x-mat-16",
    subjectId: "maths",
    chapterId: "trigonometry",
    difficulty: "easy",
    question: "The value of sin 30° + cos 60° is:",
    options: ["0", "1/2", "1", "√3/2"],
    answer: 2,
    explanation: "sin 30° = 1/2 and cos 60° = 1/2, so the sum is 1.",
    concept: "Standard angles",
  },
  {
    id: "x-mat-17",
    subjectId: "maths",
    chapterId: "trigonometry",
    difficulty: "medium",
    question: "If tan θ = 1, then θ (0° ≤ θ ≤ 90°) equals:",
    options: ["0°", "30°", "45°", "60°"],
    answer: 2,
    explanation: "tan 45° = 1.",
    concept: "Trigonometric ratios",
  },
  {
    id: "x-mat-18",
    subjectId: "maths",
    chapterId: "trigonometry",
    difficulty: "hard",
    question: "The value of (1 − cos²θ)·cosec²θ is:",
    options: ["0", "1", "sin²θ", "tan²θ"],
    answer: 1,
    explanation: "1 − cos²θ = sin²θ, and sin²θ · cosec²θ = 1.",
    concept: "Trigonometric identities",
  },
  {
    id: "x-mat-19",
    subjectId: "maths",
    chapterId: "circles",
    difficulty: "medium",
    question: "The number of tangents that can be drawn from a point outside a circle is:",
    options: ["0", "1", "2", "Infinite"],
    answer: 2,
    explanation: "Exactly two tangents can be drawn from an external point.",
    concept: "Tangents to a circle",
  },
  {
    id: "x-mat-20",
    subjectId: "maths",
    chapterId: "circles",
    difficulty: "easy",
    question: "A tangent to a circle meets the radius at the point of contact at an angle of:",
    options: ["30°", "45°", "60°", "90°"],
    answer: 3,
    explanation: "The radius is always perpendicular to the tangent at the point of contact.",
    concept: "Tangent theorem",
  },
  {
    id: "x-mat-21",
    subjectId: "maths",
    chapterId: "surface-areas",
    difficulty: "medium",
    question: "The total surface area of a sphere of radius 7 cm is (take π = 22/7):",
    options: ["154 cm²", "308 cm²", "616 cm²", "1232 cm²"],
    answer: 2,
    explanation: "4πr² = 4 × 22/7 × 49 = 616 cm².",
    concept: "Surface area of a sphere",
  },
  {
    id: "x-mat-22",
    subjectId: "maths",
    chapterId: "surface-areas",
    difficulty: "hard",
    question: "A solid metallic sphere is melted and recast into smaller spheres. What remains unchanged?",
    options: ["Radius", "Surface area", "Volume", "Number of spheres"],
    answer: 2,
    explanation: "In melting and recasting, total volume of metal is conserved.",
    concept: "Conversion of solids",
  },
  {
    id: "x-mat-23",
    subjectId: "maths",
    chapterId: "statistics",
    difficulty: "easy",
    question: "The mode of the data 3, 5, 5, 7, 9 is:",
    options: ["3", "5", "7", "9"],
    answer: 1,
    explanation: "Mode is the value occurring most often, which is 5.",
    concept: "Mode",
  },
  {
    id: "x-mat-24",
    subjectId: "maths",
    chapterId: "statistics",
    difficulty: "medium",
    question: "The empirical relation between mean, median and mode is:",
    options: [
      "Mode = 3 Median − 2 Mean",
      "Mode = 2 Median − 3 Mean",
      "Mean = 3 Median − 2 Mode",
      "Median = 3 Mode − 2 Mean",
    ],
    answer: 0,
    explanation: "The empirical relationship is 3 Median = Mode + 2 Mean, i.e. Mode = 3 Median − 2 Mean.",
    concept: "Empirical relation",
  },
  {
    id: "x-mat-25",
    subjectId: "maths",
    chapterId: "probability",
    difficulty: "easy",
    question: "The probability of getting a head when a fair coin is tossed once is:",
    options: ["0", "1/4", "1/2", "1"],
    answer: 2,
    explanation: "There are two equally likely outcomes, so P(head) = 1/2.",
    concept: "Simple probability",
  },
  {
    id: "x-mat-26",
    subjectId: "maths",
    chapterId: "probability",
    difficulty: "medium",
    question: "A die is thrown once. The probability of getting a prime number is:",
    options: ["1/6", "1/3", "1/2", "2/3"],
    answer: 2,
    explanation: "Primes on a die are 2, 3 and 5, so P = 3/6 = 1/2.",
    concept: "Probability with dice",
  },
  {
    id: "x-mat-27",
    subjectId: "maths",
    chapterId: "probability",
    difficulty: "hard",
    question: "One card is drawn from a well-shuffled deck. The probability that it is a red king is:",
    options: ["1/13", "1/26", "1/52", "2/13"],
    answer: 1,
    explanation: "There are 2 red kings out of 52 cards, so P = 2/52 = 1/26.",
    concept: "Probability with cards",
  },

  // -------------------------------------------------------------------- SST
  {
    id: "x-sst-1",
    subjectId: "sst",
    chapterId: "nationalism-europe",
    difficulty: "medium",
    question: "Who was proclaimed the German Emperor in 1871 at Versailles?",
    options: ["Otto von Bismarck", "Kaiser William I", "Giuseppe Mazzini", "Count Cavour"],
    answer: 1,
    explanation: "Kaiser William I of Prussia was proclaimed German Emperor in January 1871.",
    concept: "Unification of Germany",
  },
  {
    id: "x-sst-2",
    subjectId: "sst",
    chapterId: "nationalism-europe",
    difficulty: "easy",
    question: "'Young Italy' was a secret society founded by:",
    options: ["Garibaldi", "Mazzini", "Cavour", "Metternich"],
    answer: 1,
    explanation: "Giuseppe Mazzini founded Young Italy in Marseilles.",
    concept: "Revolutionaries in Europe",
  },
  {
    id: "x-sst-3",
    subjectId: "sst",
    chapterId: "nationalism-india",
    difficulty: "medium",
    question: "The Jallianwala Bagh massacre took place in:",
    options: ["1917", "1919", "1920", "1930"],
    answer: 1,
    explanation: "General Dyer ordered firing on a peaceful gathering in Amritsar on 13 April 1919.",
    concept: "Rowlatt Satyagraha",
  },
  {
    id: "x-sst-4",
    subjectId: "sst",
    chapterId: "nationalism-india",
    difficulty: "easy",
    question: "The Civil Disobedience Movement began with:",
    options: ["Chauri Chaura incident", "Dandi March", "Quit India Movement", "Simon Commission"],
    answer: 1,
    explanation: "Gandhiji's Salt March to Dandi in 1930 launched the Civil Disobedience Movement.",
    concept: "Civil Disobedience Movement",
  },
  {
    id: "x-sst-5",
    subjectId: "sst",
    chapterId: "nationalism-india",
    difficulty: "hard",
    question: "The Non-Cooperation Movement was called off after the:",
    options: ["Jallianwala Bagh massacre", "Chauri Chaura incident", "Poona Pact", "Lahore Session"],
    answer: 1,
    explanation: "Gandhiji withdrew the movement in February 1922 after violence at Chauri Chaura.",
    concept: "Non-Cooperation Movement",
  },
  {
    id: "x-sst-6",
    subjectId: "sst",
    chapterId: "resources",
    difficulty: "medium",
    question: "Black soil is best suited for the cultivation of:",
    options: ["Rice", "Cotton", "Tea", "Coffee"],
    answer: 1,
    explanation: "Black (regur) soil retains moisture well and is ideal for cotton.",
    concept: "Soil types",
  },
  {
    id: "x-sst-7",
    subjectId: "sst",
    chapterId: "resources",
    difficulty: "easy",
    question: "Which of the following is a renewable resource?",
    options: ["Coal", "Petroleum", "Solar energy", "Natural gas"],
    answer: 2,
    explanation: "Solar energy is continuously replenished and hence renewable.",
    concept: "Classification of resources",
  },
  {
    id: "x-sst-8",
    subjectId: "sst",
    chapterId: "water-resources",
    difficulty: "medium",
    question: "Sardar Sarovar Dam is built on the river:",
    options: ["Godavari", "Narmada", "Krishna", "Mahanadi"],
    answer: 1,
    explanation: "The Sardar Sarovar project is on the Narmada river in Gujarat.",
    concept: "Multipurpose river projects",
  },
  {
    id: "x-sst-9",
    subjectId: "sst",
    chapterId: "water-resources",
    difficulty: "hard",
    question: "'Tankas' for rainwater harvesting are traditionally found in:",
    options: ["Meghalaya", "Rajasthan", "Kerala", "Assam"],
    answer: 1,
    explanation: "Underground tankas store rainwater in the semi-arid regions of Rajasthan.",
    concept: "Rainwater harvesting",
  },
  {
    id: "x-sst-10",
    subjectId: "sst",
    chapterId: "power-sharing",
    difficulty: "easy",
    question: "The community government of Belgium is elected by:",
    options: [
      "The central parliament",
      "People belonging to one language community",
      "The King",
      "State governors",
    ],
    answer: 1,
    explanation: "Belgium's community government is elected by people of one language community — Dutch, French or German.",
    concept: "Belgian model",
  },
  {
    id: "x-sst-11",
    subjectId: "sst",
    chapterId: "power-sharing",
    difficulty: "medium",
    question: "Majoritarianism in Sri Lanka led to:",
    options: [
      "Equal rights for Tamils",
      "Alienation of Sri Lankan Tamils and civil war",
      "Federal government",
      "Recognition of Tamil as the only official language",
    ],
    answer: 1,
    explanation: "Sinhala-only policies alienated Tamils and eventually led to civil war.",
    concept: "Majoritarianism",
  },
  {
    id: "x-sst-12",
    subjectId: "sst",
    chapterId: "federalism",
    difficulty: "medium",
    question: "Defence and foreign affairs are included in the:",
    options: ["State List", "Union List", "Concurrent List", "Residuary subjects"],
    answer: 1,
    explanation: "Subjects of national importance are in the Union List.",
    concept: "Division of powers",
  },
  {
    id: "x-sst-13",
    subjectId: "sst",
    chapterId: "federalism",
    difficulty: "hard",
    question: "The 1992 constitutional amendment in India is important because it:",
    options: [
      "Created new states",
      "Made three-tier local government constitutionally mandatory",
      "Abolished the Rajya Sabha",
      "Changed the official language",
    ],
    answer: 1,
    explanation: "The 73rd and 74th amendments of 1992 made panchayats and municipalities mandatory.",
    concept: "Decentralisation",
  },
  {
    id: "x-sst-14",
    subjectId: "sst",
    chapterId: "development",
    difficulty: "medium",
    question: "Human Development Report is published by:",
    options: ["World Bank", "UNDP", "IMF", "WTO"],
    answer: 1,
    explanation: "The United Nations Development Programme publishes the HDR every year.",
    concept: "Human Development Index",
  },
  {
    id: "x-sst-15",
    subjectId: "sst",
    chapterId: "development",
    difficulty: "easy",
    question: "The average income of a country is also called:",
    options: ["Total income", "Per capita income", "National wealth", "Gross profit"],
    answer: 1,
    explanation: "Per capita income = national income ÷ total population.",
    concept: "Income as a development indicator",
  },
  {
    id: "x-sst-16",
    subjectId: "sst",
    chapterId: "sectors-economy",
    difficulty: "medium",
    question: "MGNREGA 2005 guarantees employment for:",
    options: ["50 days", "100 days", "150 days", "200 days"],
    answer: 1,
    explanation: "It guarantees 100 days of wage employment in a year to rural households.",
    concept: "Right to work",
  },
  {
    id: "x-sst-17",
    subjectId: "sst",
    chapterId: "sectors-economy",
    difficulty: "easy",
    question: "Banking and insurance belong to the:",
    options: ["Primary sector", "Secondary sector", "Tertiary sector", "Informal sector"],
    answer: 2,
    explanation: "Services that support production come under the tertiary sector.",
    concept: "Sectors of the economy",
  },
  {
    id: "x-sst-18",
    subjectId: "sst",
    chapterId: "sectors-economy",
    difficulty: "hard",
    question: "Disguised unemployment is mostly found in the:",
    options: ["Organised sector", "Agricultural sector", "IT sector", "Public sector"],
    answer: 1,
    explanation: "In agriculture, more people work on a field than actually needed, so their contribution is negligible.",
    concept: "Underemployment",
  },

  // ---------------------------------------------------------------- ENGLISH
  {
    id: "x-eng-1",
    subjectId: "english",
    chapterId: "first-flight",
    difficulty: "easy",
    question: "In 'A Letter to God', Lencho wrote a letter to God asking for:",
    options: ["Food", "A hundred pesos", "A new house", "Rain"],
    answer: 1,
    explanation: "Lencho asked God for a hundred pesos to sow his field again after the hailstorm.",
    concept: "A Letter to God",
  },
  {
    id: "x-eng-2",
    subjectId: "english",
    chapterId: "first-flight",
    difficulty: "medium",
    question: "Nelson Mandela's autobiography is titled:",
    options: ["Wings of Fire", "Long Walk to Freedom", "My Experiments with Truth", "The Story of My Life"],
    answer: 1,
    explanation: "'Long Walk to Freedom' is Mandela's autobiography.",
    concept: "Nelson Mandela",
  },
  {
    id: "x-eng-3",
    subjectId: "english",
    chapterId: "poems",
    difficulty: "medium",
    question: "In 'Fire and Ice', 'ice' symbolises:",
    options: ["Desire", "Hatred", "Love", "Fear"],
    answer: 1,
    explanation: "Frost uses fire for desire and ice for hatred or indifference.",
    concept: "Fire and Ice",
  },
  {
    id: "x-eng-4",
    subjectId: "english",
    chapterId: "poems",
    difficulty: "easy",
    question: "Who wrote the poem 'Dust of Snow'?",
    options: ["Robert Frost", "John Berryman", "Carolyn Wells", "Walt Whitman"],
    answer: 0,
    explanation: "'Dust of Snow' was written by Robert Frost.",
    concept: "Dust of Snow",
  },
  {
    id: "x-eng-5",
    subjectId: "english",
    chapterId: "footprints",
    difficulty: "medium",
    question: "In 'A Triumph of Surgery', Tricki suffered mainly because of:",
    options: ["An accident", "Overfeeding and lack of exercise", "A viral infection", "Old age"],
    answer: 1,
    explanation: "Mrs Pumphrey overfed Tricki and gave him no exercise, making him ill.",
    concept: "A Triumph of Surgery",
  },
  {
    id: "x-eng-6",
    subjectId: "english",
    chapterId: "footprints",
    difficulty: "easy",
    question: "The narrator of 'The Thief's Story' is:",
    options: ["Anil", "Hari Singh", "A shopkeeper", "A policeman"],
    answer: 1,
    explanation: "The story is narrated by the young thief Hari Singh.",
    concept: "The Thief's Story",
  },
  {
    id: "x-eng-7",
    subjectId: "english",
    chapterId: "grammar",
    difficulty: "easy",
    question: "Choose the correct sentence:",
    options: [
      "He don't like tea.",
      "He doesn't likes tea.",
      "He doesn't like tea.",
      "He not like tea.",
    ],
    answer: 2,
    explanation: "With a third-person singular subject we use 'doesn't' followed by the base verb.",
    concept: "Subject–verb agreement",
  },
  {
    id: "x-eng-8",
    subjectId: "english",
    chapterId: "grammar",
    difficulty: "medium",
    question: "Reported speech of: She said, \"I am busy today.\"",
    options: [
      "She said that she is busy today.",
      "She said that she was busy that day.",
      "She said that I was busy today.",
      "She says that she was busy that day.",
    ],
    answer: 1,
    explanation: "Present tense becomes past and 'today' becomes 'that day' in reported speech.",
    concept: "Reported speech",
  },
  {
    id: "x-eng-9",
    subjectId: "english",
    chapterId: "grammar",
    difficulty: "hard",
    question: "Fill in the blank: If it ____ tomorrow, we will cancel the match.",
    options: ["rains", "will rain", "rained", "is raining"],
    answer: 0,
    explanation: "In a first conditional, the if-clause takes the simple present.",
    concept: "Conditionals",
  },
  {
    id: "x-eng-10",
    subjectId: "english",
    chapterId: "writing",
    difficulty: "medium",
    question: "A formal letter to an editor should NOT include:",
    options: ["Sender's address", "Subject line", "Informal slang", "Date"],
    answer: 2,
    explanation: "Formal letters must use a polite, impersonal register without slang.",
    concept: "Formal letter format",
  },
  {
    id: "x-eng-11",
    subjectId: "english",
    chapterId: "writing",
    difficulty: "easy",
    question: "An analytical paragraph is usually written in:",
    options: ["First person, casual tone", "Third person, formal tone", "Dialogue form", "Poetic form"],
    answer: 1,
    explanation: "Analytical paragraphs interpret data objectively in a formal, third-person tone.",
    concept: "Analytical paragraph",
  },

  // ------------------------------------------------------------------ HINDI
  {
    id: "x-hin-1",
    subjectId: "hindi",
    chapterId: "kshitij-kavya",
    difficulty: "medium",
    question: "'सूरदास' के पदों में किस रस की प्रधानता है?",
    options: ["वीर रस", "वियोग शृंगार", "हास्य रस", "करुण रस"],
    answer: 1,
    explanation: "सूरदास के भ्रमरगीत के पदों में गोपियों का वियोग शृंगार प्रमुख है।",
    concept: "सूरदास के पद",
  },
  {
    id: "x-hin-2",
    subjectId: "hindi",
    chapterId: "kshitij-kavya",
    difficulty: "easy",
    question: "'राम-लक्ष्मण-परशुराम संवाद' के रचयिता कौन हैं?",
    options: ["सूरदास", "तुलसीदास", "जयशंकर प्रसाद", "निराला"],
    answer: 1,
    explanation: "यह प्रसंग तुलसीदास कृत रामचरितमानस से लिया गया है।",
    concept: "तुलसीदास",
  },
  {
    id: "x-hin-3",
    subjectId: "hindi",
    chapterId: "kshitij-gadya",
    difficulty: "medium",
    question: "'बालगोबिन भगत' पाठ के लेखक हैं:",
    options: ["रामवृक्ष बेनीपुरी", "यशपाल", "मन्नू भंडारी", "स्वयं प्रकाश"],
    answer: 0,
    explanation: "'बालगोबिन भगत' रेखाचित्र रामवृक्ष बेनीपुरी ने लिखा है।",
    concept: "लेखक परिचय",
  },
  {
    id: "x-hin-4",
    subjectId: "hindi",
    chapterId: "kshitij-gadya",
    difficulty: "hard",
    question: "'लखनवी अंदाज़' पाठ किस विधा में लिखा गया है?",
    options: ["कहानी", "व्यंग्य", "निबंध", "संस्मरण"],
    answer: 1,
    explanation: "यशपाल का 'लखनवी अंदाज़' नवाबी दिखावे पर एक व्यंग्य है।",
    concept: "विधा",
  },
  {
    id: "x-hin-5",
    subjectId: "hindi",
    chapterId: "kritika",
    difficulty: "medium",
    question: "'माता का अँचल' पाठ के लेखक कौन हैं?",
    options: ["शिवपूजन सहाय", "मधु कांकरिया", "रवींद्र केलेकर", "महादेवी वर्मा"],
    answer: 0,
    explanation: "'माता का अँचल' शिवपूजन सहाय द्वारा लिखा गया है।",
    concept: "कृतिका",
  },
  {
    id: "x-hin-6",
    subjectId: "hindi",
    chapterId: "kritika",
    difficulty: "easy",
    question: "'साना साना हाथ जोड़ि' यात्रा-वृत्तांत किस राज्य से संबंधित है?",
    options: ["हिमाचल प्रदेश", "सिक्किम", "उत्तराखंड", "असम"],
    answer: 1,
    explanation: "मधु कांकरिया ने सिक्किम की यात्रा का वर्णन किया है।",
    concept: "यात्रा वृत्तांत",
  },
  {
    id: "x-hin-7",
    subjectId: "hindi",
    chapterId: "vyakaran",
    difficulty: "easy",
    question: "'विद्यालय' शब्द में कौन-सी संधि है?",
    options: ["गुण संधि", "दीर्घ संधि", "वृद्धि संधि", "यण संधि"],
    answer: 1,
    explanation: "विद्या + आलय = विद्यालय, आ + आ = आ होने से दीर्घ संधि है।",
    concept: "संधि",
  },
  {
    id: "x-hin-8",
    subjectId: "hindi",
    chapterId: "vyakaran",
    difficulty: "medium",
    question: "'चरण-कमल बंदौं हरिराई' पंक्ति में कौन-सा अलंकार है?",
    options: ["उपमा", "रूपक", "अनुप्रास", "यमक"],
    answer: 1,
    explanation: "चरणों में कमल का आरोप होने के कारण यहाँ रूपक अलंकार है।",
    concept: "अलंकार",
  },
  {
    id: "x-hin-9",
    subjectId: "hindi",
    chapterId: "vyakaran",
    difficulty: "hard",
    question: "'जो व्यक्ति परिश्रम करता है, वह सफल होता है।' यह वाक्य है:",
    options: ["सरल वाक्य", "संयुक्त वाक्य", "मिश्र वाक्य", "प्रश्नवाचक वाक्य"],
    answer: 2,
    explanation: "इसमें एक मुख्य उपवाक्य और एक आश्रित उपवाक्य है, अतः यह मिश्र वाक्य है।",
    concept: "रचना के आधार पर वाक्य",
  },
];
